DIC_COUNTRY = {
    "Abkhazian": "ab",
    "Afar": "aa",
    "Afrikaans": "af",
    "Akan": "ak",
    "Akkadian": "akk",
    "Albanian": "sq",
    "American Sign Language": "ase",
    "Amharic": "am",
    "Arabic": "ar",
    "Aramaic": "arc",
    "Armenian": "hy",
    "Assamese": "as",
    "Aymara": "ay",
    "Azerbaijani": "az",
    "Bambara": "bm",
    "Bangla": "bn",
    "Bangla (India)": "bn",
    "Bashkir": "ba",
    "Basque": "eu",
    "Belarusian": "be",
    "Bhojpuri": "bho",
    "Bislama": "bi",
    "Bodo": "brx",
    "Bosnian": "bs",
    "Breton": "br",
    "Bulgarian": "bg",
    "Burmese": "my",
    "Cantonese": "yue",
    "Cantonese (Hong Kong)": "yue-Hant-HK",
    "Catalan": "ca",
    "Cherokee": "chr",
    "Chinese": "zh",
    "Chinese (China)": "zh",
    "Chinese (Hong Kong)": "zh",
    "Chinese (Simplified)": "zh",
    "Chinese (Singapore)": "zh",
    "Chinese (Taiwan)": "zh",
    "Chinese (Traditional)": "zh",
    "Choctaw": "cho",
    "Coptic": "cop",
    "Corsican": "co",
    "Cree": "cr",
    "Croatian": "hr",
    "Czech": "cs",
    "Danish": "da",
    "Dogri": "doi",
    "Dutch": "nl",
    "Dutch (Belgium)": "nl",
    "Dutch (Netherlands)": "nl",
    "Dzongkha": "dz",
    "English": "en",
    "English (Australia)": "en",
    "English (Canada)": "en",
    "English (India)": "en",
    "English (Ireland)": "en",
    "English (United Kingdom)": "en",
    "English (United States)": "en",
    "Esperanto": "eo",
    "Estonian": "et",
    "Ewe": "ee",
    "Faroese": "fo",
    "Fijian": "fj",
    "Filipino": "fil",
    "Finnish": "fi",
    "French": "fr",
    "French (Belgium)": "fr",
    "French (Canada)": "fr",
    "French (France)": "fr",
    "French (Switzerland)": "fr",
    "Fula": "ff",
    "Galician": "gl",
    "Ganda": "lg",
    "Georgian": "ka",
    "German": "de",
    "German (Austria)": "de",
    "German (Germany)": "de",
    "German (Switzerland)": "de",
    "Greek": "el",
    "Guarani": "gn",
    "Gujarati": "gu",
    "Gusii": "guz",
    "Haitian Creole": "ht",
    "Hakka Chinese": "hak",
    "Hakka Chinese (Taiwan)": "hak",
    "Haryanvi": "bgc",
    "Hausa": "ha",
    "Hawaiian": "haw",
    "Hebrew": "he",
    "Hindi": "hi",
    "Hindi (Latin)": "hi",
    "Hiri Motu": "ho",
    "Hungarian": "hu",
    "Icelandic": "is",
    "Igbo": "ig",
    "Indonesian": "id",
    "Interlingua": "ia",
    "Interlingue": "ie",
    "Inuktitut": "iu",
    "Inupiaq": "ik",
    "Irish": "ga",
    "Italian": "it",
    "Japanese": "ja",
    "Javanese": "jv",
    "Kalaallisut": "kl",
    "Kalenjin": "kln",
    "Kamba": "kam",
    "Kannada": "kn",
    "Kashmiri": "ks",
    "Kazakh": "kk",
    "Khmer": "km",
    "Kikuyu": "ki",
    "Kinyarwanda": "rw",
    "Klingon": "tlh",
    "Konkani": "kok",
    "Korean": "ko",
    "Kurdish": "ku",
    "Kyrgyz": "ky",
    "Ladino": "lad",
    "Lao": "lo",
    "Latin": "la",
    "Latvian": "lv",
    "Lingala": "ln",
    "Lithuanian": "lt",
    "Luba-Katanga": "lu",
    "Luo": "luo",
    "Luxembourgish": "lb",
    "Luyia": "luy",
    "Macedonian": "mk",
    "Maithili": "mai",
    "Malagasy": "mg",
    "Malay": "ms",
    "Malay (Singapore)": "ms",
    "Malayalam": "ml",
    "Maltese": "mt",
    "Manipuri": "mni",
    "Māori": "mi",
    "Marathi": "mr",
    "Masai": "mas",
    "Meru": "mer",
    "Min Nan Chinese": "nan",
    "Min Nan Chinese (Taiwan)": "nan",
    "Mixe": "mix",
    "Mizo": "lus",
    "Mongolian": "mn",
    "Mongolian (Mongolian)": "mn",
    "Nauru": "na",
    "Navajo": "nv",
    "Nepali": "ne",
    "Nigerian Pidgin": "pcm",
    "North Ndebele": "nd",
    "Northern Sotho": "nso",
    "Norwegian": "no",
    "Occitan": "oc",
    "Odia": "or",
    "Oromo": "om",
    "Papiamento": "pap",
    "Pashto": "ps",
    "Persian": "fa",
    "Persian (Afghanistan)": "fa",
    "Persian (Iran)": "fa",
    "Polish": "pl",
    "Portuguese": "pt",
    "Portuguese (Brazil)": "pt",
    "Portuguese (Portugal)": "pt",
    "Punjabi": "pa",
    "Quechua": "qu",
    "Romanian": "ro",
    "Romanian (Moldova)": "ro",
    "Romansh": "rm",
    "Rundi": "rn",
    "Russian": "ru",
    "Russian (Latin)": "ru",
    "Samoan": "sm",
    "Sango": "sg",
    "Sanskrit": "sa",
    "Santali": "sat",
    "Sardinian": "sc",
    "Scottish Gaelic": "gd",
    "Serbian": "sr",
    "Serbian (Cyrillic)": "sr",
    "Serbian (Latin)": "sr",
    "Serbo-Croatian": "sh",
    "Sherdukpen": "sdp",
    "Shona": "sn",
    "Sicilian": "scn",
    "Sindhi": "sd",
    "Sinhala": "si",
    "Slovak": "sk",
    "Slovenian": "sl",
    "Somali": "so",
    "South Ndebele": "nr",
    "Southern Sotho": "st",
    "Spanish": "es",
    "Spanish (Latin America)": "es",
    "Spanish (Mexico)": "es",
    "Spanish (Spain)": "es",
    "Spanish (United States)": "es",
    "Sundanese": "su",
    "Swahili": "sw",
    "Swati": "ss",
    "Swedish": "sv",
    "Tagalog": "tl",
    "Tajik": "tg",
    "Tamil": "ta",
    "Tatar": "tt",
    "Telugu": "te",
    "Thai": "th",
    "Tibetan": "bo",
    "Tigrinya": "ti",
    "Tok Pisin": "tpi",
    "Toki Pona": "tokipona",
    "Tongan": "to",
    "Tsonga": "ts",
    "Tswana": "tn",
    "Turkish": "tr",
    "Turkmen": "tk",
    "Twi": "tw",
    "Ukrainian": "uk",
    "Urdu": "ur",
    "Uyghur": "ug",
    "Uzbek": "uz",
    "Venda": "ve",
    "Vietnamese": "vi",
    "Volapük": "vo",
    "Võro": "vro",
    "Welsh": "cy",
    "Western Frisian": "fy",
    "Wolaytta": "wal",
    "Wolof": "wo",
    "Xhosa": "xh",
    "Yiddish": "yi",
    "Yoruba": "yo",
    "Zulu": "zu"
}

def get_country_code(country):
    return DIC_COUNTRY.get(country, "en")
