name: Daily Deployment

on:
    schedule:
        - cron: '0 18 * * *'
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name:
              uses: actions/checkout@v2
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: '3.11'
            - name: Install dependencies
              run: |
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt
            - name: Run deployment script
              run: python main.py


