name: Daily Deployment

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 18 * * *'

run-name: Deploy
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      YT_IS_ENABLE_OTP: ${{ secrets.YT_IS_ENABLE_OTP }}
      YT_GOOGLE_EMAIL: ${{ secrets.YT_GOOGLE_EMAIL }}
      YT_GOOGLE_PASSWORD: ${{ secrets.YT_GOOGLE_PASSWORD }}
      YT_TELEGRAM_BOT_TOKEN : ${{ secrets.YT_TELEGRAM_BOT_TOKEN }}
      YT_TELEGRAM_CHAT_ID : ${{ secrets.YT_TELEGRAM_CHAT_ID }}

    permissions: write-all
    steps:
        - name: Checkout Code
          uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.11'
            cache: 'pip'
            architecture: 'x64'
        - name: Install dependencies
          run: pip install -r requirements.txt
        - name: Run deployment script
          run: python src/main.py
        - name: Upload artifact
          uses: actions/upload-artifact@v4
          with:
            name: yt-artifact
            path: output
            if-no-files-found: error
